# SPDX-License-Identifier: MIT
---

__keylime_server_legacy_config: false

# ansible_facts required by the role
__keylime_server_required_facts:
  - distribution
  - distribution_major_version
  - distribution_version
  - os_family

# the subsets of ansible_facts that need to be gathered in case any of the
# facts in required_facts is missing; see the documentation of
# the 'gather_subset' parameter of the 'setup' module
__keylime_server_required_facts_subsets: "{{ ['!all', '!min'] + __keylime_server_required_facts }}"

__keylime_server_write_log_file: false

__keylime_server_packages:
  - keylime-verifier
  - keylime-registrar

__keylime_server_verifier_service: keylime_verifier
__keylime_server_registrar_service: keylime_registrar

__keylime_server_user: keylime
__keylime_server_group: keylime

# Default database configuration.
__keylime_server_verifier_default_db: sqlite
__keylime_server_registrar_default_db: sqlite

__keylime_server_verifier_snippet_dir: /etc/keylime/verifier.conf.d
__keylime_server_registrar_snippet_dir: /etc/keylime/registrar.conf.d

__keylime_server_verifier_ip_config: verifier-ip.conf
__keylime_server_verifier_database_config: verifier-database.conf
__keylime_server_verifier_keys_certs_config: verifier-keys-certs.conf

__keylime_server_registrar_ip_config: registrar-ip.conf
__keylime_server_registrar_database_config: registrar-database.conf
__keylime_server_registrar_keys_certs_config: registrar-keys-certs.conf

# time, in seconds, to wait for the verifier and registrar
# services to become available
__keylime_service_timeout: 30

# BEGIN - DO NOT EDIT THIS BLOCK - rh distros variables
# Ansible distribution identifiers that the role treats like RHEL
__keylime_server_rh_distros:
  - AlmaLinux
  - CentOS
  - RedHat
  - Rocky

# Same as above but includes Fedora
__keylime_server_rh_distros_fedora: "{{ __keylime_server_rh_distros + ['Fedora'] }}"

# Use this in conditionals to check if distro is Red Hat or clone
__keylime_server_is_rh_distro: "{{ ansible_facts['distribution'] in __keylime_server_rh_distros }}"

# Use this in conditionals to check if distro is Red Hat or clone, or Fedora
__keylime_server_is_rh_distro_fedora: "{{ ansible_facts['distribution'] in __keylime_server_rh_distros_fedora }}"

# Use these in conditionals to check if distro is Red Hat or clone of a specific major version
__keylime_server_is_rh_distro_7: "{{ __keylime_server_is_rh_distro and ansible_facts['distribution_major_version'] == '7' }}"
__keylime_server_is_rh_distro_8: "{{ __keylime_server_is_rh_distro and ansible_facts['distribution_major_version'] == '8' }}"
__keylime_server_is_rh_distro_9: "{{ __keylime_server_is_rh_distro and ansible_facts['distribution_major_version'] == '9' }}"
__keylime_server_is_rh_distro_10: "{{ __keylime_server_is_rh_distro and ansible_facts['distribution_major_version'] == '10' }}"
# END - DO NOT EDIT THIS BLOCK - rh distros variables
