#SPDX-License-Identifier: MIT-0
---
# tasks file for myvhost
##########################################
# 패키지 설치 - httpd, mod_ssl
# 서비스 기동 - httpd
# 서비스 설정
# * /var/www/vhosts/{{ inventory_hostname }} 디렉토리 생성
# * index.html --copy--> /var/www/vhosts/{{ inventory_hostname }}/index.html
# 서비스 기동
# 서비스 설정
# * vhost.conf.j2 --template--> /var/www/vhosts/{{ inventory_hostname}}/vhost.conf.j2
#   => notify ~ handler
##########################################
- name: 패키지 설치 - httpd, mod_ssl
  ansible.builtin.dnf:
    name:
      - httpd
      - mod_ssl
    state: present

- name: 서비스 설정 - /var/www/vhosts/{{ ansible_facts["hostname"] }} 디렉토리 생성
  ansible.builtin.file:
    path: /var/www/vhosts/{{ ansible_facts["hostname"] }}
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: 서비스 설정 - /var/www/vhosts/{{ ansible_facts["hostname"] }}/index.html 파일 생성
  ansible.builtin.copy:
    src: index.html
    dest: "/var/www/vhosts/{{ ansible_facts['hostname'] }}/index.html"
    mode: '0644'

- name: 서비스 기동 - httpd
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - httpd

- name: 서비스 설정 - /etc/httpd/conf.d/vhost.conf
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart httpd
