# SPDX-License-Identifier: MIT
---
- name: Run augenrules
  ansible.builtin.command:
    cmd: augenrules
  changed_when: true
  notify: Load audit rules

- name: Load audit rules
  ansible.builtin.command:
    cmd: augenrules --load
  changed_when: true
  when:
    - auditd_start_service | bool
    - ansible_connection not in ["container", "docker", "community.docker.docker"]

- name: Restart auditd
  ansible.builtin.service:
    name: "{{ __auditd_service }}"
    state: restarted
    use: service
  when: auditd_start_service | bool
