---
##################################
# Play01 - 하드웨어 보고서 작성
# 1) 파일 배포
# 2) 파일 편집
# 3) 파일 수집
##################################
- name: Play01 - 하드웨어 보고서 작성
  hosts: all
  tasks:
    # 1) 파일 배포
    # files/hwreport.txt -> ansible#:/root/hwreport.txt
    - name: 1) 파일 배포
      ansible.builtin.copy:
        src:  files/hwreport.txt
        dest: /root/hwreport.txt
        owner:  root
        group:  root  
        mode: '0600'

    # 2) 파일 편집
    - name: 2) 파일 편집 - INVENTORY_HOSTNAME
      ansible.builtin.replace:
        path: /root/hwreport.txt
        regexp: 'inventoryhostname'
        replace: "{{ inventory_hostname }}"

    # 2) 파일 편집
    - name: 2) 파일 편집 - TOTAL_MEM
      ansible.builtin.replace:
        path: /root/hwreport.txt
        regexp: 'totalmem'
        replace: "{{ ansible_memtotal_mb }}"

        # 2) 파일 편집
    - name: 2) 파일 편집 - BIOS_VER
      ansible.builtin.lineinfile:
        path: /root/hwreport.txt
        regexp: 'biosversion'
        line: "BIOS_VER = {{ ansible_bios_version }}"

    # 2) 파일 편집
    - name: 2) 파일 편집 - SDA_SIZE
      ansible.builtin.lineinfile:
        path: /root/hwreport.txt
        regexp: 'sdasize'
        line: "SDA_SIZE = {{ ansible_facts['devices']['nvme0n1']['size'] }}"

    # 3) 파일 수집
    - name: 3) 파일 수집
      ansible.builtin.fetch:
        src: /root/hwreport.txt
        #dest: results/{{  inventory_hostname }}-hwreport.txt
        dest: results
        flat: false