---
- name: 0) 작업 제어 실습
  hosts: webservers
  gather_facts: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: 0) 점검, (ㄱ)메모리 점검 (ㄴ)배포판 종류 점검
      ansible.builtin.fail:
        msg: "[ FAIL ] 메모리가 256M 보다 작거나 CentOS가 아닙니다."
      when: >
        ansible_facts["memtotal_mb"] < min_ram_mb or
        ansible_facts["distribution"] != "CentOS"

    - name: 0) 다른 점검, (ㄷ)배포판 버전 점검
      ansible.builtin.debug:
        msg: "CentOS Stream 10버전에서만 동작합니다."
      failed_when: ansible_facts["distribution_version"] != "10"

    - name: 1) 패키지 설치 - {{ packages }}
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present

    - name: 2) 서비스 기동 - {{ services }}
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ services }}"

    - name: Block ~ rescue
      block:
        - name: 3) 웹 서버 설정
          ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: "{{ item.owner }}"
            group: "{{ item.group }}"
            mode: "{{ item.mode | string }}"
          loop: "{{ web_config_files }}"
          notify: restart_web_service
      rescue:
        - name: 3) 웹 서버 설정 - 에러메세지 출력
          ansible.builtin.debug:
            msg: "[ FAIL ] 웹 서버 설정이 잘못 되었습니다."

    - name: 4) 방화벽에 포트 등록
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ firewall_rules }}"

  handlers:
    - name: restart_web_service
      ansible.builtin.systemd_service:
        name: "{{ web_service }}"
        state: restarted