---
# Task File:
- name: 웹 파일 생성 - {{ file }}
  ansible.builtin.copy:
    content: |
      <pre>
      IP: "{{ ansible_facts['default_ipv4']['address'] }}"
      HOST: "{{ ansible_facts['fqdn'] }}"
      </pre>
    dest: "{{ file }}"
    mode: '0644'
