---
###############################################
# Play 01:
# 1) 웹서버 패키지 설치 및 서비스 기동 - include_tasks
# 2) 방화벽 패키지 설치 및 서비스 기동, 포트 등록 - import_tasks
# 3) 웹서버 설정(/var/www/html/index.html) - import_tasks
# Play 02:
# 4) 웹요청 - import_playbook
###############################################
- name: 웹 서버 설정
  hosts: webservers
  tasks:
    - name: 1) 웹서버 패키지 설치 및 서비스 기동
      ansible.builtin.include_tasks: tasks/web.yml
      vars:
        packages:
          - httpd
          - mod_ssl
        service: httpd
      #when: ansible_facts['os_family'] == 'CentOS'
      when: ansible_os_family == 'RedHat'

    - name: 2) 방화벽 패키지 설치 및 서비스 기동, 포트 등록
      ansible.builtin.import_tasks: tasks/fw.yml
      vars:
        packages: firewalld
        service: firewalld
        rules:
          - http
          - https

    - name: 3) 웹서버 설정(/var/www/html/index.html)
      ansible.builtin.import_tasks: tasks/placeholder.yml
      vars:
        file: /var/www/html/index.html

- name: 웹요청
  ansible.builtin.import_playbook: plays/test.yml
  vars:
    url: "http://ansible1.example.com"
