download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/containers-podman-1.20.2.tar.gz
format_version: 1.0.0
name: podman
namespace: containers
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.20.2
version_url: /api/content/published/v3/plugin/ansible/content/published/collections/index/containers/podman/versions/1.20.2/
