---
- name: Play 01) EPEL 패키지 설치
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: 1) epel-release 패키지 설치
      ansible.builtin.include_tasks: ../05_vars-inclusions/install_package.yml
      vars:
        package:
          web_pkg: epel-release

    - name: 2) cowsay 패키지 설치
      # (주의) cowsay 패키지는 반드시 epel-release 패키지 설치 이후에 설치해야 한다.
      ansible.builtin.include_tasks: ../05_vars-inclusions/install_package.yml
      vars:
        package:
          web_pkg: cowsay
