# SPDX-License-Identifier: MIT
---
- name: Deploy Trustee Guest Components using Podman Quadlets from GitHub repository
  hosts: all
  vars:
    trustee_client_encrypt_disk: false
    trustee_client_kbs_url: "https://kbs.example.com"
# Use either cert content or path to cert file:
    trustee_client_kbs_cert_content: "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"
# trustee_client_kbs_cert_src: "/path/to/server.crt"
    trustee_client_secret_registration_enabled: false
  roles:
    - fedora.linux_system_roles.trustee_client
