---
- name: 0) 모듈 테스트 - 파일 삭제 
  hosts: all
  gather_facts: false
  tasks:
    - name: 1) 파일 삭제
      ansible.builtin.file:
        path: /home/devops/users.txt
        line: '추가된 라인'
        state: adsent
