# SPDX-License-Identifier: MIT
---
- name: Reload systemd daemon for trustee
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "restart trustee services"

- name: Enable and restart trustee services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: restarted
  loop: "{{ __trustee_client_services | default([]) }}"
  listen: "restart trustee services"
