# SPDX-License-Identifier: MIT
---
- name: Configure auditd with custom log retention and an exit path rule
  hosts: all
  vars:
    auditd_num_logs: 5
    auditd_max_log_file: 16
    auditd_flush: incremental_async
    auditd_freq: 50
    auditd_rules:
      - action: always
        filter: exit
        arch: b64
        syscall: open
        path: /etc/passwd
        permission:
          - read
          - write
          - attribute_change
        keyname: passwd_watch
  roles:
    - fedora.linux_system_roles.auditd
