---
- name: create user accounts for all our servers
  hosts: devservers
  remote_user:  devops
  become: true
  vars_files:
    - vars/secret1.yml
    - vars/secret2.yml
    - vars/secret3.yml
  tasks:
    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
      loop: "{{ newusers1 + newusers2 + newusers3 }}"