# SPDX-License-Identifier: MIT
---
- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

- name: Validate role parameters
  ansible.builtin.include_tasks: assert_role_vars.yml

- name: Deploy Trustee Guest Components using Podman Quadlets
  include_tasks: trustee_quadlet.yml
  when: trustee_client_trustee_gc | bool

- name: Deploy Secret Registration Client Service
  include_tasks: secret_registration_client.yml
  when:
    - trustee_client_secret_registration_enabled | bool
    - trustee_client_trustee_gc | bool

- name: Create encrypted disk partition
  include_tasks: encrypt_disk.yml
  when:
    - trustee_client_encrypt_disk | bool

- name: Record role success fingerprint
  fedora.linux_system_roles.sr_fingerprint:
    status: success
    role_name: trustee_client
    role_path: "{{ role_path }}"
    ansible_play_hosts_all: "{{ ansible_play_hosts_all }}"
    distribution: "{{ ansible_facts['distribution'] }}"
    distribution_version: "{{ ansible_facts['distribution_version'] }}"
    write_log_file: "{{ __trustee_client_write_log_file }}"
