---
 ##############################
# Play 01 - 웹 서버 구축
# 1) 패키지 설치
# 2) 서비스 설정
# 3) 서비스 기동
# 4) 방화벽에 등록
# Play 02 - 웹 요청 확인
##############################
#
# Play 01 - 웹 서버 설정
#
- name: Play01 - 웹서버 설정
  hosts: webservers
  vars:
    pkg_http:  httpd
    pkg_https: mod_ssl
    pkg_fw: firewalld
    inx_dest: /var/www/html/index.html
    svc_web: httpd
    svc_fw: firewalld
    fw_80: http
    fw_8080: https
   
  tasks:
    # 1) 웹패키지 설치 - httpd, mod_ssl, firewalld
    - name: 1) 웹패키지 설치
      ansible.builtin.dnf:
        name:
          - "{{ pkg_http }}"
          - "{{ pkg_https }}"
          - "{{ pkg_fw }}"
        state: present
    # 2) 웹서비스 설정 - /var/www/html/index.html
    - name: 2) 웹 서버 설정 - /var/www/html/index.html
      ansible.builtin.copy:
        content: "web1.example.com\n"
        dest: "{{ inx_dest }}"
        mode: '0644'

    # 3) 웹서비스 기동 - httpd, firewalld
    - name: 웹서비스 기동 - "{{ svc_web }}", "{{ svc_fw }}"
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - "{{ svc_web }}"
        - "{{ svc_fw }}"

    # 4) 방화벽에 등록
    - name: 4) 방화벽에 등록
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: true
      loop:
        - "{{ fw_80 }}"
        - "{{ fw_8080 }}"


- name: 1) 웹 확인
  hosts: localhost
  become: false
  vars:
     url_web1: http://192.168.10.11
  tasks:
    - name: 웹 요청
      ansible.builtin.uri:
        url: "{{ url_web1 }}"
        return_content: true
      register: resp
    
    
    - name: 2) HTML reponse
      ansible.builtin.debug:
        var: resp["content"]