# SPDX-License-Identifier: MIT
---
galaxy_info:
  author: Li Tian <litian@redhat.com>
  description: Ansible role for setting up confidential virtual machine deployments
  company: Red Hat, Inc.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - trustee
    - attestation
    - el9
    - el10
    - fedora
    # Support running this role in system container environments, and enable
    # tests. Remove if not applicable.
    # - container
    # Support running this role during container builds (mostly useful for
    # bootc), and enable tests. Remove if not applicable.
    # - containerbuild
dependencies: []
