---
##########################
# Play01 - DB 서비스 기동
# 1) 패키지 설치 - mariadb-server, python3-PyMySQL
# 2) 서비스 기동 - maraidb
###########################
- name: Restore playbook.yml
  hosts: all
  gather_facts: true
  vars:
    db_pkgs:
      - mariadb
      - mariadb-server
      - python3-PyMySQL
    db_svc: mariadb
  tasks:
    - name: 1) 서비스 중지 - mariadb
      ansible.builtin.systemd_service:
        name: "{{ db_svc }}"
        state:  stopped
        enabled: false

    - name: 2) 패키지 삭제 - mariadb, mariadb-server, python3-PyMySQL
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop: "{{ db_pkgs }}"
      when: ansible_facts["distribution"] == "CentOS"


    
        